// Generated by https://quicktype.io

export interface IVideoPage {
	userInfo: UserInfo;
	title: string;
	video: string;
	docsInfo: DocsInfo;
	reviewInfo: ReviewInfo[];
	bookmarkInfo: BookmarkInfo[];
	curriculumInfo: CurriculumInfo[];
}

export interface BookmarkInfo {
	usersId: number;
	bookmarkId: number;
	memo: string;
	createdAt: string;
	modifiedAt: null;
	timeLine: null;
}

export interface CurriculumInfo {
	chapterId: number;
	chapterOrder: string;
	title: string;
	uploadClassList: UploadClassList[];
}

export interface UploadClassList {
	uploadClassId: number;
	title: string;
}

export interface DocsInfo {
	docsId: number;
	details: string;
	name: string;
}

export interface ReviewInfo {
	usersId: number;
	userName: string;
	profileImage: string;
	reviewId: number;
	starRate: number;
	comments: string;
	createdAt: string;
	modifiedAt: null;
}

export interface UserInfo {
	usersId: number;
	email: string;
	userName: string;
	profileImage: string;
}

// // Generated by https://quicktype.io

// export interface IVideoPage {
// 	userInfo: UserInfo;
// 	title: string;
// 	video: string;
// 	docsInfo: DocsInfo;
// 	reviewInfo: ReviewInfo[];
// 	bookmarkInfo: BookmarkInfo[];
// 	curriculumInfo: CurriculumInfo[];
// }

// export interface BookmarkInfo {
// 	usersId: number;
// 	bookmarkId: number;
// 	memo: string;
// 	createdAt: string;
// 	modifiedAt: null;
// }

// export interface CurriculumInfo {
// 	chapterId: number;
// 	chapterOrder: string;
// 	title: string;
// 	uploadClassList: UploadClassList[];
// }

// export interface UploadClassList {
// 	uploadClassId: number;
// 	title: string;
// }

// export interface DocsInfo {
// 	docsId: number;
// 	details: string;
// 	name: string;
// }

// export interface ReviewInfo {
// 	usersId: number;
// 	reviewId: number;
// 	starRate: number;
// 	comments: string;
// 	createdAt: string;
// 	modifiedAt: string;
// }

// export interface UserInfo {
// 	usersId: number;
// 	email: string;
// 	userName: string;
// 	profileImage: string;
// }
