// Generated by https://quicktype.io

export interface ILoopIDList {
	contentsId: number;
	chapterList: ChapterList[];
}
[];

export interface ChapterList {
	chapterId: number;
	uploadClassList: number[];
}
