name: node.js CI

on:
   push:
      branches: ['dev-fe']

jobs:
   build:
      runs-on: self-hosted
      defaults:
         run:
            working-directory: ./client/

      strategy:
         matrix:
            node-version: [16.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
         - uses: actions/checkout@v3
           with:
              path: 'client'
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v3
           with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
         - run: cd client && npm i
         - run: cd client && npm run build --if-present
