name: class-next-nginx-deploy

on:
   push:
      branches: ['dev-fe', 'fe/test/yaml-production-test']

jobs:
   build:
      runs-on: self-hosted

      strategy:
         matrix:
            node-version: [16.x]

      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v3
           with:
              node-version: ${{ matrix.node-version }}
         - run: cd client && npm i
         - run: |
              cd ~
              pwd
              sudo ./env_inject.sh
         - run: cd client && npm run build --if-present
         - run: |
              cd client
              pm2 stop 0
              pm2 start 0
              pm2 save
              sudo service nginx restart
